<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Error Page</title>
<style>
.all{
border:2px dashed green;
width:777px;
margin:20px auto;
padding:1px;
font-weight:bold;
}
.up{
background-color:#DEDEDE;
color:blue;
font-size:33px;
text-align:center;
}
.main{
margin:20px 0;
}
.down{
background-color:#DEDEDE;
color:blue;
font-size:33px;
text-align:center;
}
</style>
</head>
<body>
	<div class="all">
		<div class="up">Oh, god! Error!</div>
		<div class="main">error</div>
		<div class="down">Friend! Don't be discouraged!</div>
	</div>
</body>
</html>